blank_issues_enabled: false
contact_links:
  - name: The program won't run/can't install
    url: https://github.com/seanpm2001/Git-image/tree/main/Docs/Installation/
    about: This question will be ignored if asked. Please read the docs.
  - name: I want to help develop
    url: https://github.com/seanpm2001/Teams/discussions/
    about: Thank you for your interest in this project! Please consider joining a team to start developing with me
  - name: Why?/What is the point?
    url: https://github.com/seanpm2001/Git-image/tree/main/Docs/Purpose/
    about: This document goes over the purpose of the Git-image process
  - name: I want to help translate
    url: https://github.com/seanpm2001/Teams/discussions/
    about: Thank you for your interest in this project! Please consider joining a team to start translating projects with me

# File info
# File version: 1 (2022, Thursday, May 19th at 3:08 pm PST)
# File type: GitHub issue template config file (*.yml)
# Line count (including blank lines and compiler line): 20
